### PR TITLE
Updateable classes

### PR DESCRIPTION
**Pull request by winescout**
1. makes sessions updatable on homepage
2. separates out the old registration.js file into angular components
3. adds HighVoltage for templates, and mounts them under /templates

### CODE REVIEW

**Comment by orangewolf** [comment]
@winescout I really disagree with the high voltage change. You are removing useful functionality and replacing it with a gem that doesn't do anything the router doesn't do automatically.

**Comment by winescout** [comment]
Ok, sounds like we need to talk about this.  Here is the use case.  I'm open to better suggestions.  HV is the simplest solution I know about.

I need a way to easily drop in templates for the Angular application to load.  I do not want to have to modify manifest files or anything like that.  HV is nice because I can drop them in to the pages directly, and HV handles the routing.

**Comment by winescout** [comment]
I've restored the Pages controller, and moved angular templates to /templates.

**Comment by orangewolf** [comment]
You also did a bunch of other edits that conflict with things we agreed I would do. I though we worked together? Am I wrong about that?

**Comment by winescout** [comment]
Dude, I was trying to help you

**Pull request closed without merging**
